CREATE TABLE IF NOT EXISTS Images
(
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME image_id_seq START WITH 1),
    title       varchar(255) NOT NULL,
    alt         varchar(255) NOT NULL,
    description text,
    image_path  varchar(255) NOT NULL,
    created_at  date         NOT NULL,
    updated_at  date         NOT NULL
);