CREATE TABLE IF NOT EXISTS Communities
(
    id                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME community_id_seq START WITH 1),
    name              varchar(100) NOT NULL UNIQUE,
    description       text,
    banner_path       varchar(255),
    avatar_path       varchar(255),
    owner_id          integer NOT NULL,
    number_of_members integer               default (0),
    number_of_posts   integer               default (0),
    created_at        timestamp    NOT NULL default (CURRENT_TIMESTAMP),
    FOREIGN KEY (owner_id) REFERENCES Users (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CommunityModerator
(
    id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME community_moderator_id_seq START WITH 1),
    community_id integer NOT NULL,
    user_id      integer NOT NULL,
    FOREIGN KEY (community_id) REFERENCES Communities (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CommunityMember
(
    id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME community_member_id_seq START WITH 1),
    community_id integer NOT NULL,
    user_id      integer NOT NULL,
    FOREIGN KEY (community_id) REFERENCES Communities (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CommunityTag
(
    id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME community_tag_id_seq START WITH 1),
    community_id integer      NOT NULL,
    tag          varchar(100) NOT NULL,
    FOREIGN KEY (community_id) REFERENCES Communities (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CommunityCategory
(
    id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME community_category_id_seq START WITH 1),
    community_id integer NOT NULL,
    category_id  integer NOT NULL,
    FOREIGN KEY (community_id) REFERENCES Communities (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (category_id) REFERENCES Categories (id) ON DELETE CASCADE ON UPDATE CASCADE
)
