CREATE TABLE IF NOT EXISTS Posts
(
    id                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME post_id_seq START WITH 1),
    title             varchar(100) NOT NULL,
    content           text,
    author_id         integer NOT NULL,
    community_id      integer,
    views             integer               default (0),
    likes             integer               default (0),
    dislikes          integer               default (0),
    created_at        timestamp    NOT NULL default (CURRENT_TIMESTAMP),
    updated_at        timestamp    NOT NULL default (CURRENT_TIMESTAMP),
    FOREIGN KEY (author_id) REFERENCES Users (id) ON UPDATE CASCADE,
    FOREIGN KEY (community_id) REFERENCES Communities (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PostTag
(
    id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME post_tag_id_seq START WITH 1),
    post_id integer      NOT NULL,
    tag          varchar(100) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES Posts (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PostCategory
(
    id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME post_category_id_seq START WITH 1),
    post_id integer NOT NULL,
    category_id  integer NOT NULL,
    FOREIGN KEY (post_id) REFERENCES Posts (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (category_id) REFERENCES Categories (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PostImage
(
    id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME post_image_id_seq START WITH 1),
    post_id integer NOT NULL,
    image_id  integer NOT NULL,
    FOREIGN KEY (post_id) REFERENCES Posts (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (image_id) REFERENCES Images (id) ON DELETE CASCADE ON UPDATE CASCADE
)
